name: CodSpeed Benchmarks

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install pytest pytest-codspeed  pytest-benchmark
          # Install the package from setup.py
          pip install .
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest test/ --codspeed -v
