name: CodSpeed Benchmarks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v7

      - name: "Set up Python"
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: uv run pytest --codspeed tests/benchmarks/
